### ISSUE TITLE
Add a proper README

### ISSUE THREAD

**Issue by Anth0rx** [Taose/Vegastrike-taose#118]
Hey Taose,
I stumbled upon your fork and I do like the fact that finally there seems to be an effort in further develop Vegastrike. So thank you very much for that.
What I was missing when I first visited your repository is a proper README. This probably seems like a little exaggerated for creating an issue, but I also wanted to use this opportunity to thank you and offer my help (although I am not the best programmer). Vegastrike seems to be the most mature free software project regarding space simulation.

**Comment by Taose** [comment]
Hi there! The reason why there is no read me is because the later versions haven't been "approved" yet. You should find some read me available later on. That said, if you would like to add to it or completely re do it and for that matter add to the code, you're more than welcome to do so.

**Comment by Anth0rx** [comment]
The first question would be what to add to the README. I kinda would add something like the introducion part of the wiki here.

**Comment by Taose** [comment]
Sounds like a good idea, would you like a shot at putting it into practice?

**Comment by Anth0rx** [comment]
Sure, I will compose a README and will create a PR for reviewing.

**Comment by Taose** [comment]
Reclaimed one that we had in the experimental branch. 

509cc3ce0a81

However, you're more than welcome to replace or modify it.
