### ISSUE TITLE
Move to VegaStrike GitHub org?

### ISSUE THREAD

**Issue by BenjamenMeyer** [Taose/Vegastrike-taose#97]
Any interest in working with https://github.com/vegastrike?

**Comment by Taose** [comment]
Neither the SVN nor the official Github repository has had an update since 2011, the Github repository has not moved from its original upload commit. I think what I'd personally be looking for here is: Why? 

In principle I'm interested, that's the official Github repository for the official Vegastrike game after all and working with the real developers on improving the game and getting the bugs out of the way is a great thing. Therein of course, lies the problem. 

That's of course, the reason this fork got started, Vega Strike appeared to be abandoned at its very core. (Except Loki... who is still wandering the forums). Given how far the fork has come, it's not going to be so easy to just merge pull the changes either.

**Comment by BenjamenMeyer** [comment]
@Taose I'm working with @ermo (https://github.com/ermo/privateer_wcu/issues/1) as well; I'd like to try to bring things back together to a single effort instead of the 3+ different efforts going on. At the moment, I'm just orchestrating and any tips, etc from you would be appreciated as well.

**Comment by Taose** [comment]
As far as I can tell, Privateer is a mod and my version is not significantly different from the "official" version to cause any major issues as I am more than happy to follow their lead for the moment...if there was a lead to follow. 

What Vega Strike needs and what at the moment it is lacking, are skilled coders. Within which we can wrap up a package and re-submit to the various linux repositories. This will hopefully attract other skilled and amateur coders to contribute content, overhaul a few things and above all get the community alive again. 

From my perspective, I am far more interested in the "Simulation" application that Vega Strike has a good deal of potential for. There is a good deal of potential here to both learn and teach about how physics are in space and what a space ship might have to deal with and what potentially day to day travel may look like one day. 

I think potentially, one of the things that Vega Strike suffered with, was community management, perhaps through some sense of ownership and lack of direction. This meant that coders eventually drifted away and no focus on getting into the repositories was a disaster for the community, coupled with attrition from devs naturally ceasing work on Vega Strike (as in the way with community projects) we find ourselves where we are today. I have a few ideas in mind how to resolve "some" of those issues, for instance by getting some kind of "reward" scheme of some kind set up and also focus on stuff that is more run of the mill like testing. Testing is under-rated. Of course it's not the be all and end all, but if you want to produce a complex game like this, you need to test to no end. 

Well, that's mostly just my opinion from what I've been reading, whether any of that is actually the case I have no idea. All I know was that before I started poking around the dust looked well and truly settled and I'm glad that some coders are still around and interested. I know that the IRC still has a few people in there. 

Oh and as soon as Eye~R (Suterusu) gets his server up and running, I envisage server days...that I so plan to make mandatory participation... gotta get that participation rate up!

**Comment by Taose** [comment]
As no further changes have been made to the original Github since 2015, there doesn't seem to be a case justifying a move to that one. 

If the situation changes in the future and development returns, I'd be more than happy to reconsider my decision.

For now, it's a no.

**Comment by BenjamenMeyer** [comment]
understandable; thanks for the release BTW.
